version: '3'

services:
  web:
    image: maki/modx
    depends_on:
      - db
    links:
      - db:mysql
    ports:
      - 8000:80
    environment:
      MODX_VERSION: 2.7.0
      MODX_DB_HOST: mysql:3306
      MODX_DB_PASSWORD: modx
      MODX_DB_USER: modx
      MODX_DB_NAME: modx
    volumes:
      - ./html:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: modx
      MYSQL_USER: modx
      MYSQL_PASSWORD: modx
    command: mysqld --sql-mode=NO_ENGINE_SUBSTITUTION
    volumes:
      - ./mysql:/var/lib/mysql
